name: Auto Commit and Push

on:
  schedule:
    - cron: "36 1 * * *"

  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Make Multiple Commits
        run: |
          git config --global user.name "Murad Lalayev" 
          git config --global user.email "lalayevmurad@gmail.com"
          
          # 5 farklı commit yapmak için döngü
          for i in {1..5}
          do
            echo "Commit $i - $(date)" >> update.log
            git add update.log
            git commit -m "Auto update $i - $(date)"
            sleep 2 
          done

          git push
